//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Dom Editor automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.Utils.Categories.DOM.Model
{
	using System;
	using System.ComponentModel;

	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Sections;

	public static class SlcCategoriesIds
	{
		public const string ModuleId = "(slc)categories";
		public static class Enums
		{
		}

		public static class Sections
		{
			public static class CategoryInfo
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("5816d327-e025-4f2f-a404-fd0685a6d047"))
				{ ModuleId = "(slc)categories" };
				public static FieldDescriptorID Name { get; } = new FieldDescriptorID(new Guid("68bea0c6-e645-4605-ad7e-31ea31802d77"));
				public static FieldDescriptorID ParentCategory { get; } = new FieldDescriptorID(new Guid("fdc3efdc-cd13-4e9e-bf31-7aeb58702813"));
			}
		}

		public static class Definitions
		{
			public static DomDefinitionId Category { get; } = new DomDefinitionId(new Guid("51561163-340a-4953-97e0-bec5418fb559"))
			{ ModuleId = "(slc)categories" };
		}

		public static class Behaviors
		{
		}
	}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Dom Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.Utils.Categories.DOM.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Messages;

	/// <summary>
	/// Represents a wrapper class for accessing a CategoryInstance DOM instance.
	/// The <see cref="CategoryInstance"/> class provides simplified access to the data and functionality of the underlying DOM instance, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	public partial class CategoryInstance : DomInstanceBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="CategoryInstance"/> class. Creates an empty <see cref="CategoryInstance"/> instance with default settings.
		/// </summary>
		public CategoryInstance() : base(SlcCategoriesIds.Definitions.Category)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="CategoryInstance"/> class. Creates an empty <see cref="CategoryInstance"/> instance with default settings and a specific ID.
		/// </summary>
		public CategoryInstance(Guid id) : base(SlcCategoriesIds.Definitions.Category, id)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="CategoryInstance"/> class using the specified <paramref name="domInstance"/> for initializing the object.
		/// </summary>
		/// <param name="domInstance">The <see cref="DomInstance"/> object that provides data for initializing the <see cref="CategoryInstance"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public CategoryInstance(DomInstance domInstance) : base(domInstance)
		{
			if (!domInstance.DomDefinitionId.Equals(SlcCategoriesIds.Definitions.Category))
				throw new ArgumentException($"The given domInstance, is not of type '{nameof(SlcCategoriesIds.Definitions.Category)}'", nameof(domInstance));
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Gets or sets the CategoryInfo section of the DOM Instance.
		/// </summary>
		public CategoryInfoSection CategoryInfo { get; set; }

		public static explicit operator CategoryInstance(DomInstance instance)
		{
			return new CategoryInstance(instance);
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="CategoryInstance"/>.
		/// </summary>
		/// <returns>A new <see cref="CategoryInstance"/> object that is a deep copy of this instance.</returns>
		public CategoryInstance Clone()
		{
			return new CategoryInstance((DomInstance)this.ToInstance().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="CategoryInstance"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="CategoryInstance"/> object that is a copy of this instance but with a different id.</returns>
		public CategoryInstance Duplicate()
		{
			var instance = (DomInstance)this.ToInstance().Clone();
			instance.ID = new DomInstanceId(Guid.NewGuid())
			{ ModuleId = ModuleId };
			foreach (var section in instance.Sections)
			{
				section.ID = new Skyline.DataMiner.Net.Sections.SectionID(Guid.NewGuid());
			}

			return new CategoryInstance(instance);
		}

		/// <inheritdoc />
		protected sealed override DomInstance InternalToInstance()
		{
			domInstance.Sections.Clear();
			domInstance.Sections.Add(CategoryInfo.ToSection());
			return domInstance;
		}

		/// <inheritdoc />
		public sealed override void Save(DomHelper helper)
		{
			var exist = helper.DomInstances.Read(DomInstanceExposers.Id.Equal(domInstance.ID)).FirstOrDefault();
			var instance = ToInstance();
			if (exist == null)
			{
				domInstance = helper.DomInstances.Create(instance);
			}
			else
			{
				domInstance = helper.DomInstances.Update(instance);
			}
		}

		protected sealed override void InitializeProperties()
		{
			var _categoryInfo = domInstance.Sections.FirstOrDefault(section => section.SectionDefinitionID.Equals(SlcCategoriesIds.Sections.CategoryInfo.Id));
			if (_categoryInfo is null)
			{
				CategoryInfo = new CategoryInfoSection();
			}
			else
			{
				CategoryInfo = new CategoryInfoSection(_categoryInfo);
			}
		}
	}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DOM Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.Utils.Categories.DOM.Model
{
	using System;
	using System.Collections.Generic;
	using System.Collections.ObjectModel;
	using System.Linq;

	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Apps.Sections.Sections;
	using Skyline.DataMiner.Net.Messages;
	using Skyline.DataMiner.Net.Sections;

	/// <summary>
	/// Represents a wrapper class for accessing a CategoryInfoSection section.
	/// The <see cref="CategoryInfoSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	public partial class CategoryInfoSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="CategoryInfoSection"/> class. Creates an empty <see cref="CategoryInfoSection"/> object with default settings.
		/// </summary>
		public CategoryInfoSection() : base(SlcCategoriesIds.Sections.CategoryInfo.Id)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="CategoryInfoSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="CategoryInfoSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public CategoryInfoSection(Section section) : base(section, SlcCategoriesIds.Sections.CategoryInfo.Id)
		{
		}

		/// <summary>
		/// Gets or sets the Name field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String Name
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcCategoriesIds.Sections.CategoryInfo.Name);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcCategoriesIds.Sections.CategoryInfo.Name);
				}
				else
				{
					section.AddOrUpdateValue(SlcCategoriesIds.Sections.CategoryInfo.Name, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the ParentCategory field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Guid? ParentCategory
		{
			get
			{
				var wrapper = section.GetValue<Guid>(SlcCategoriesIds.Sections.CategoryInfo.ParentCategory);
				if (wrapper != null)
				{
					return (Guid?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcCategoriesIds.Sections.CategoryInfo.ParentCategory);
				}
				else
				{
					section.AddOrUpdateValue(SlcCategoriesIds.Sections.CategoryInfo.ParentCategory, (Guid)value);
				}
			}
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="CategoryInfoSection"/>.
		/// </summary>
		/// <returns>A new <see cref="CategoryInfoSection"/> object that is a deep copy of this section.</returns>
		public CategoryInfoSection Clone()
		{
			return new CategoryInfoSection((Section)this.ToSection().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="CategoryInfoSection"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="CategoryInfoSection"/> object that is a copy of this section but with a different id.</returns>
		public CategoryInfoSection Duplicate()
		{
			var section = (Section)this.ToSection().Clone();
			section.ID = new SectionID(Guid.NewGuid());
			return new CategoryInfoSection(section);
		}

		/// <inheritdoc />
		protected override Section InternalToSection()
		{
			if (section.GetValue<String>(SlcCategoriesIds.Sections.CategoryInfo.Name) == null)
				throw new InvalidOperationException("'Name' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			return section;
		}
	}
}

