//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Dom Editor automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.Solutions.Categories.DOM.Model
{
	using System;
	using System.ComponentModel;

	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Sections;

	internal static class SlcCategoriesIds
	{
		public const string ModuleId = "(slc)categories";
		internal static class Enums
		{
		}

		internal static class Sections
		{
			internal static class CategoryItemInfo
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("2ae55ec4-695d-4605-b4f4-a219ccfd1637"))
				{ ModuleId = "(slc)categories" };
				public static FieldDescriptorID Category { get; } = new FieldDescriptorID(new Guid("85bb3e12-6f69-4ac3-ba49-3a0824bb4161"));
				public static FieldDescriptorID ModuleID { get; } = new FieldDescriptorID(new Guid("9f694734-ce4e-4bf1-b22a-9bdca55f0da1"));
				public static FieldDescriptorID InstanceID { get; } = new FieldDescriptorID(new Guid("cb6a5cae-5522-43e7-990f-493b4d77f9be"));
			}

			internal static class ScopeInfo
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("63e9aabd-f09a-4c46-9dff-1167f6d456d3"))
				{ ModuleId = "(slc)categories" };
				public static FieldDescriptorID Name { get; } = new FieldDescriptorID(new Guid("5d75a4ad-05b8-4770-9266-97afddcb62bb"));
			}

			internal static class CategoryInfo
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("5816d327-e025-4f2f-a404-fd0685a6d047"))
				{ ModuleId = "(slc)categories" };
				public static FieldDescriptorID Name { get; } = new FieldDescriptorID(new Guid("68bea0c6-e645-4605-ad7e-31ea31802d77"));
				public static FieldDescriptorID ParentCategory { get; } = new FieldDescriptorID(new Guid("fdc3efdc-cd13-4e9e-bf31-7aeb58702813"));
				public static FieldDescriptorID Scope { get; } = new FieldDescriptorID(new Guid("285f102e-7a6a-46b0-98ea-67d3affdb14c"));
			}
		}

		internal static class Definitions
		{
			public static DomDefinitionId Category { get; } = new DomDefinitionId(new Guid("51561163-340a-4953-97e0-bec5418fb559"))
			{ ModuleId = "(slc)categories" };
			public static DomDefinitionId Scope { get; } = new DomDefinitionId(new Guid("e8e3d37b-0db4-4ef8-83ec-7d36db215e13"))
			{ ModuleId = "(slc)categories" };
			public static DomDefinitionId CategoryItem { get; } = new DomDefinitionId(new Guid("b9418eb6-ed00-4eac-a186-c5468de33389"))
			{ ModuleId = "(slc)categories" };
		}

		internal static class Behaviors
		{
		}
	}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Dom Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.Solutions.Categories.DOM.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Messages;

	/// <summary>
	/// Represents a wrapper class for accessing a CategoryInstance DOM instance.
	/// The <see cref="CategoryInstance"/> class provides simplified access to the data and functionality of the underlying DOM instance, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class CategoryInstance : DomInstanceBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="CategoryInstance"/> class. Creates an empty <see cref="CategoryInstance"/> instance with default settings.
		/// </summary>
		public CategoryInstance() : base(SlcCategoriesIds.Definitions.Category)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="CategoryInstance"/> class. Creates an empty <see cref="CategoryInstance"/> instance with default settings and a specific ID.
		/// </summary>
		public CategoryInstance(Guid id) : base(SlcCategoriesIds.Definitions.Category, id)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="CategoryInstance"/> class using the specified <paramref name="domInstance"/> for initializing the object.
		/// </summary>
		/// <param name="domInstance">The <see cref="DomInstance"/> object that provides data for initializing the <see cref="CategoryInstance"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public CategoryInstance(DomInstance domInstance) : base(domInstance)
		{
			if (!domInstance.DomDefinitionId.Equals(SlcCategoriesIds.Definitions.Category))
				throw new ArgumentException($"The given domInstance, is not of type '{nameof(SlcCategoriesIds.Definitions.Category)}'", nameof(domInstance));
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Gets or sets the CategoryInfo section of the DOM Instance.
		/// </summary>
		public CategoryInfoSection CategoryInfo { get; set; }

		public static explicit operator CategoryInstance(DomInstance instance)
		{
			return new CategoryInstance(instance);
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="CategoryInstance"/>.
		/// </summary>
		/// <returns>A new <see cref="CategoryInstance"/> object that is a deep copy of this instance.</returns>
		public CategoryInstance Clone()
		{
			return new CategoryInstance((DomInstance)this.ToInstance().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="CategoryInstance"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="CategoryInstance"/> object that is a copy of this instance but with a different id.</returns>
		public CategoryInstance Duplicate()
		{
			var instance = (DomInstance)this.ToInstance().Clone();
			instance.ID = new DomInstanceId(Guid.NewGuid())
			{ ModuleId = ModuleId };
			foreach (var section in instance.Sections)
			{
				section.ID = new Skyline.DataMiner.Net.Sections.SectionID(Guid.NewGuid());
			}

			return new CategoryInstance(instance);
		}

		/// <inheritdoc />
		protected sealed override DomInstance InternalToInstance()
		{
			domInstance.Sections.Clear();
			domInstance.Sections.Add(CategoryInfo.ToSection());
			return domInstance;
		}

		/// <inheritdoc />
		public sealed override void Save(DomHelper helper)
		{
			var exist = helper.DomInstances.Read(DomInstanceExposers.Id.Equal(domInstance.ID)).FirstOrDefault();
			var instance = ToInstance();
			if (exist == null)
			{
				domInstance = helper.DomInstances.Create(instance);
			}
			else
			{
				domInstance = helper.DomInstances.Update(instance);
			}
		}

		protected sealed override void InitializeProperties()
		{
			var _categoryInfo = domInstance.Sections.FirstOrDefault(section => section.SectionDefinitionID.Equals(SlcCategoriesIds.Sections.CategoryInfo.Id));
			if (_categoryInfo is null)
			{
				CategoryInfo = new CategoryInfoSection();
			}
			else
			{
				CategoryInfo = new CategoryInfoSection(_categoryInfo);
			}
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a ScopeInstance DOM instance.
	/// The <see cref="ScopeInstance"/> class provides simplified access to the data and functionality of the underlying DOM instance, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class ScopeInstance : DomInstanceBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="ScopeInstance"/> class. Creates an empty <see cref="ScopeInstance"/> instance with default settings.
		/// </summary>
		public ScopeInstance() : base(SlcCategoriesIds.Definitions.Scope)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="ScopeInstance"/> class. Creates an empty <see cref="ScopeInstance"/> instance with default settings and a specific ID.
		/// </summary>
		public ScopeInstance(Guid id) : base(SlcCategoriesIds.Definitions.Scope, id)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="ScopeInstance"/> class using the specified <paramref name="domInstance"/> for initializing the object.
		/// </summary>
		/// <param name="domInstance">The <see cref="DomInstance"/> object that provides data for initializing the <see cref="ScopeInstance"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public ScopeInstance(DomInstance domInstance) : base(domInstance)
		{
			if (!domInstance.DomDefinitionId.Equals(SlcCategoriesIds.Definitions.Scope))
				throw new ArgumentException($"The given domInstance, is not of type '{nameof(SlcCategoriesIds.Definitions.Scope)}'", nameof(domInstance));
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Gets or sets the ScopeInfo section of the DOM Instance.
		/// </summary>
		public ScopeInfoSection ScopeInfo { get; set; }

		public static explicit operator ScopeInstance(DomInstance instance)
		{
			return new ScopeInstance(instance);
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="ScopeInstance"/>.
		/// </summary>
		/// <returns>A new <see cref="ScopeInstance"/> object that is a deep copy of this instance.</returns>
		public ScopeInstance Clone()
		{
			return new ScopeInstance((DomInstance)this.ToInstance().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="ScopeInstance"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="ScopeInstance"/> object that is a copy of this instance but with a different id.</returns>
		public ScopeInstance Duplicate()
		{
			var instance = (DomInstance)this.ToInstance().Clone();
			instance.ID = new DomInstanceId(Guid.NewGuid())
			{ ModuleId = ModuleId };
			foreach (var section in instance.Sections)
			{
				section.ID = new Skyline.DataMiner.Net.Sections.SectionID(Guid.NewGuid());
			}

			return new ScopeInstance(instance);
		}

		/// <inheritdoc />
		protected sealed override DomInstance InternalToInstance()
		{
			domInstance.Sections.Clear();
			domInstance.Sections.Add(ScopeInfo.ToSection());
			return domInstance;
		}

		/// <inheritdoc />
		public sealed override void Save(DomHelper helper)
		{
			var exist = helper.DomInstances.Read(DomInstanceExposers.Id.Equal(domInstance.ID)).FirstOrDefault();
			var instance = ToInstance();
			if (exist == null)
			{
				domInstance = helper.DomInstances.Create(instance);
			}
			else
			{
				domInstance = helper.DomInstances.Update(instance);
			}
		}

		protected sealed override void InitializeProperties()
		{
			var _scopeInfo = domInstance.Sections.FirstOrDefault(section => section.SectionDefinitionID.Equals(SlcCategoriesIds.Sections.ScopeInfo.Id));
			if (_scopeInfo is null)
			{
				ScopeInfo = new ScopeInfoSection();
			}
			else
			{
				ScopeInfo = new ScopeInfoSection(_scopeInfo);
			}
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a CategoryItemInstance DOM instance.
	/// The <see cref="CategoryItemInstance"/> class provides simplified access to the data and functionality of the underlying DOM instance, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class CategoryItemInstance : DomInstanceBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="CategoryItemInstance"/> class. Creates an empty <see cref="CategoryItemInstance"/> instance with default settings.
		/// </summary>
		public CategoryItemInstance() : base(SlcCategoriesIds.Definitions.CategoryItem)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="CategoryItemInstance"/> class. Creates an empty <see cref="CategoryItemInstance"/> instance with default settings and a specific ID.
		/// </summary>
		public CategoryItemInstance(Guid id) : base(SlcCategoriesIds.Definitions.CategoryItem, id)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="CategoryItemInstance"/> class using the specified <paramref name="domInstance"/> for initializing the object.
		/// </summary>
		/// <param name="domInstance">The <see cref="DomInstance"/> object that provides data for initializing the <see cref="CategoryItemInstance"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public CategoryItemInstance(DomInstance domInstance) : base(domInstance)
		{
			if (!domInstance.DomDefinitionId.Equals(SlcCategoriesIds.Definitions.CategoryItem))
				throw new ArgumentException($"The given domInstance, is not of type '{nameof(SlcCategoriesIds.Definitions.CategoryItem)}'", nameof(domInstance));
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Gets or sets the CategoryItemInfo section of the DOM Instance.
		/// </summary>
		public CategoryItemInfoSection CategoryItemInfo { get; set; }

		public static explicit operator CategoryItemInstance(DomInstance instance)
		{
			return new CategoryItemInstance(instance);
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="CategoryItemInstance"/>.
		/// </summary>
		/// <returns>A new <see cref="CategoryItemInstance"/> object that is a deep copy of this instance.</returns>
		public CategoryItemInstance Clone()
		{
			return new CategoryItemInstance((DomInstance)this.ToInstance().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="CategoryItemInstance"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="CategoryItemInstance"/> object that is a copy of this instance but with a different id.</returns>
		public CategoryItemInstance Duplicate()
		{
			var instance = (DomInstance)this.ToInstance().Clone();
			instance.ID = new DomInstanceId(Guid.NewGuid())
			{ ModuleId = ModuleId };
			foreach (var section in instance.Sections)
			{
				section.ID = new Skyline.DataMiner.Net.Sections.SectionID(Guid.NewGuid());
			}

			return new CategoryItemInstance(instance);
		}

		/// <inheritdoc />
		protected sealed override DomInstance InternalToInstance()
		{
			domInstance.Sections.Clear();
			domInstance.Sections.Add(CategoryItemInfo.ToSection());
			return domInstance;
		}

		/// <inheritdoc />
		public sealed override void Save(DomHelper helper)
		{
			var exist = helper.DomInstances.Read(DomInstanceExposers.Id.Equal(domInstance.ID)).FirstOrDefault();
			var instance = ToInstance();
			if (exist == null)
			{
				domInstance = helper.DomInstances.Create(instance);
			}
			else
			{
				domInstance = helper.DomInstances.Update(instance);
			}
		}

		protected sealed override void InitializeProperties()
		{
			var _categoryItemInfo = domInstance.Sections.FirstOrDefault(section => section.SectionDefinitionID.Equals(SlcCategoriesIds.Sections.CategoryItemInfo.Id));
			if (_categoryItemInfo is null)
			{
				CategoryItemInfo = new CategoryItemInfoSection();
			}
			else
			{
				CategoryItemInfo = new CategoryItemInfoSection(_categoryItemInfo);
			}
		}
	}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DOM Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.Solutions.Categories.DOM.Model
{
	using System;
	using System.Collections.Generic;
	using System.Collections.ObjectModel;
	using System.Linq;

	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Apps.Sections.Sections;
	using Skyline.DataMiner.Net.Messages;
	using Skyline.DataMiner.Net.Sections;

	/// <summary>
	/// Represents a wrapper class for accessing a CategoryItemInfoSection section.
	/// The <see cref="CategoryItemInfoSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class CategoryItemInfoSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="CategoryItemInfoSection"/> class. Creates an empty <see cref="CategoryItemInfoSection"/> object with default settings.
		/// </summary>
		public CategoryItemInfoSection() : base(SlcCategoriesIds.Sections.CategoryItemInfo.Id)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="CategoryItemInfoSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="CategoryItemInfoSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public CategoryItemInfoSection(Section section) : base(section, SlcCategoriesIds.Sections.CategoryItemInfo.Id)
		{
		}

		/// <summary>
		/// Gets or sets the Category field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Guid? Category
		{
			get
			{
				var wrapper = section.GetValue<Guid>(SlcCategoriesIds.Sections.CategoryItemInfo.Category);
				if (wrapper != null)
				{
					return (Guid?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcCategoriesIds.Sections.CategoryItemInfo.Category);
				}
				else
				{
					section.AddOrUpdateValue(SlcCategoriesIds.Sections.CategoryItemInfo.Category, (Guid)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the ModuleID field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String ModuleID
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcCategoriesIds.Sections.CategoryItemInfo.ModuleID);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcCategoriesIds.Sections.CategoryItemInfo.ModuleID);
				}
				else
				{
					section.AddOrUpdateValue(SlcCategoriesIds.Sections.CategoryItemInfo.ModuleID, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the InstanceID field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String InstanceID
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcCategoriesIds.Sections.CategoryItemInfo.InstanceID);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcCategoriesIds.Sections.CategoryItemInfo.InstanceID);
				}
				else
				{
					section.AddOrUpdateValue(SlcCategoriesIds.Sections.CategoryItemInfo.InstanceID, (String)value);
				}
			}
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="CategoryItemInfoSection"/>.
		/// </summary>
		/// <returns>A new <see cref="CategoryItemInfoSection"/> object that is a deep copy of this section.</returns>
		public CategoryItemInfoSection Clone()
		{
			return new CategoryItemInfoSection((Section)this.ToSection().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="CategoryItemInfoSection"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="CategoryItemInfoSection"/> object that is a copy of this section but with a different id.</returns>
		public CategoryItemInfoSection Duplicate()
		{
			var section = (Section)this.ToSection().Clone();
			section.ID = new SectionID(Guid.NewGuid());
			return new CategoryItemInfoSection(section);
		}

		/// <inheritdoc />
		protected override Section InternalToSection()
		{
			if (section.GetValue<Guid>(SlcCategoriesIds.Sections.CategoryItemInfo.Category) == null)
				throw new InvalidOperationException("'Category' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<String>(SlcCategoriesIds.Sections.CategoryItemInfo.ModuleID) == null)
				throw new InvalidOperationException("'ModuleID' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			return section;
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a ScopeInfoSection section.
	/// The <see cref="ScopeInfoSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class ScopeInfoSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="ScopeInfoSection"/> class. Creates an empty <see cref="ScopeInfoSection"/> object with default settings.
		/// </summary>
		public ScopeInfoSection() : base(SlcCategoriesIds.Sections.ScopeInfo.Id)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="ScopeInfoSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="ScopeInfoSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public ScopeInfoSection(Section section) : base(section, SlcCategoriesIds.Sections.ScopeInfo.Id)
		{
		}

		/// <summary>
		/// Gets or sets the Name field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String Name
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcCategoriesIds.Sections.ScopeInfo.Name);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcCategoriesIds.Sections.ScopeInfo.Name);
				}
				else
				{
					section.AddOrUpdateValue(SlcCategoriesIds.Sections.ScopeInfo.Name, (String)value);
				}
			}
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="ScopeInfoSection"/>.
		/// </summary>
		/// <returns>A new <see cref="ScopeInfoSection"/> object that is a deep copy of this section.</returns>
		public ScopeInfoSection Clone()
		{
			return new ScopeInfoSection((Section)this.ToSection().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="ScopeInfoSection"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="ScopeInfoSection"/> object that is a copy of this section but with a different id.</returns>
		public ScopeInfoSection Duplicate()
		{
			var section = (Section)this.ToSection().Clone();
			section.ID = new SectionID(Guid.NewGuid());
			return new ScopeInfoSection(section);
		}

		/// <inheritdoc />
		protected override Section InternalToSection()
		{
			if (section.GetValue<String>(SlcCategoriesIds.Sections.ScopeInfo.Name) == null)
				throw new InvalidOperationException("'Name' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			return section;
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a CategoryInfoSection section.
	/// The <see cref="CategoryInfoSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class CategoryInfoSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="CategoryInfoSection"/> class. Creates an empty <see cref="CategoryInfoSection"/> object with default settings.
		/// </summary>
		public CategoryInfoSection() : base(SlcCategoriesIds.Sections.CategoryInfo.Id)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="CategoryInfoSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="CategoryInfoSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public CategoryInfoSection(Section section) : base(section, SlcCategoriesIds.Sections.CategoryInfo.Id)
		{
		}

		/// <summary>
		/// Gets or sets the Name field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String Name
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcCategoriesIds.Sections.CategoryInfo.Name);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcCategoriesIds.Sections.CategoryInfo.Name);
				}
				else
				{
					section.AddOrUpdateValue(SlcCategoriesIds.Sections.CategoryInfo.Name, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the ParentCategory field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Guid? ParentCategory
		{
			get
			{
				var wrapper = section.GetValue<Guid>(SlcCategoriesIds.Sections.CategoryInfo.ParentCategory);
				if (wrapper != null)
				{
					return (Guid?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcCategoriesIds.Sections.CategoryInfo.ParentCategory);
				}
				else
				{
					section.AddOrUpdateValue(SlcCategoriesIds.Sections.CategoryInfo.ParentCategory, (Guid)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the Scope field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Guid? Scope
		{
			get
			{
				var wrapper = section.GetValue<Guid>(SlcCategoriesIds.Sections.CategoryInfo.Scope);
				if (wrapper != null)
				{
					return (Guid?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcCategoriesIds.Sections.CategoryInfo.Scope);
				}
				else
				{
					section.AddOrUpdateValue(SlcCategoriesIds.Sections.CategoryInfo.Scope, (Guid)value);
				}
			}
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="CategoryInfoSection"/>.
		/// </summary>
		/// <returns>A new <see cref="CategoryInfoSection"/> object that is a deep copy of this section.</returns>
		public CategoryInfoSection Clone()
		{
			return new CategoryInfoSection((Section)this.ToSection().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="CategoryInfoSection"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="CategoryInfoSection"/> object that is a copy of this section but with a different id.</returns>
		public CategoryInfoSection Duplicate()
		{
			var section = (Section)this.ToSection().Clone();
			section.ID = new SectionID(Guid.NewGuid());
			return new CategoryInfoSection(section);
		}

		/// <inheritdoc />
		protected override Section InternalToSection()
		{
			if (section.GetValue<String>(SlcCategoriesIds.Sections.CategoryInfo.Name) == null)
				throw new InvalidOperationException("'Name' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			return section;
		}
	}
}
